// Generated by scripts/gen-content-entries.mjs — do not edit by hand.
//
// Everything m11-network needs a learner to read or run, in one module, so the
// bundler makes it one chunk that is fetched when a project here is opened.
const files = import.meta.glob('./**/*.{md,py}', {
  query: '?raw',
  import: 'default',
  eager: true,
}) as Record<string, string>

export default files
