// Pulls the web fonts local. Two reasons this matters beyond tidiness:
//
//   1. a font fetched from fonts.googleapis.com is a request that leaves the
//      origin, so the app is not actually offline
//   2. cross-origin isolation (needed later for a terminal that can block on
//      input) refuses cross-origin subresources — the fonts would silently
//      vanish and everything would fall back to system faces
import { mkdirSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const fontDir = join(root, 'public/fonts')

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36'

const FAMILIES = [
  { name: 'Inter', query: 'Inter:wght@400;500;600;700' },
  { name: 'JetBrains Mono', query: 'JetBrains+Mono:wght@400;500' },
]

mkdirSync(fontDir, { recursive: true })

let css = `/* Generated by scripts/sync-fonts.mjs — do not edit by hand. */\n`
let downloaded = 0

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`
  const source = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text())

  // Each @font-face block names one subset; keep latin and latin-ext only.
  const blocks = source.split('@font-face').slice(1)
  for (const block of blocks) {
    const subset = block.match(/\/\*\s*([\w-]+)\s*\*\//)?.[1] ?? 'latin'
    if (!['latin', 'latin-ext'].includes(subset)) continue

    const remote = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
    const weight = block.match(/font-weight:\s*([^;]+);/)?.[1].trim() ?? '400'
    const style = block.match(/font-style:\s*([^;]+);/)?.[1].trim() ?? 'normal'
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1].trim()
    if (!remote) continue

    const slug = family.name.toLowerCase().replace(/\s+/g, '-')
    const filename = `${slug}-${weight}-${subset}.woff2`
    const target = join(fontDir, filename)

    if (!existsSync(target)) {
      const bytes = Buffer.from(await (await fetch(remote)).arrayBuffer())
      writeFileSync(target, bytes)
      downloaded++
    }

    css +=
      `\n@font-face {\n` +
      `  font-family: '${family.name}';\n` +
      `  font-style: ${style};\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      // Relative to fonts.css itself, so a subpath deploy still finds them.
      `  src: url('${filename}') format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}\n`
  }
}

writeFileSync(join(fontDir, 'fonts.css'), css)

const total = readdirSync(fontDir)
  .filter((f) => f.endsWith('.woff2'))
  .reduce((sum, f) => sum + statSync(join(fontDir, f)).size, 0)

console.log(
  `fonts    ${readdirSync(fontDir).filter((f) => f.endsWith('.woff2')).length} files` +
    `${downloaded ? ` (${downloaded} downloaded)` : ' (cached)'}, ${Math.round(total / 1024)} KB`,
)
